version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
     - env
     - mvn clean
     - mvn -Dquarkus.lambda.handler=demo -Dlambdaname=demo install
     - mvn -Dquarkus.lambda.handler=dynamotest -Dlambdaname=dynamotest install
     - mkdir $S3_LAMBDA_PREFIX
     - mv target/*runner.jar $S3_LAMBDA_PREFIX
artifacts:
  files:
   - $S3_LAMBDA_PREFIX/*runner.jar
  discard-paths: no
cache:
  paths:
    - '/root/.m2/**/*'